spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # Put here your user name
    username: root
    # Put here your password
    password: '123123ivaka'
    url: jdbc:mysql://localhost:3306/watch_shop_project?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    #    For MySQL 8 uncomment bellow (comment MySQL 5)
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5 (innodb dialect below)
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
            enabled: true

cloudinary:
  cloud-name: watch-shop-cloud
  api-key: 696194539816934
  api-secret: "${CLOUDINARY_SECRET}"